// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zopdjsagvwmygtjpwwqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvcGRqc2FndndteWd0anB3d3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTU0ODYsImV4cCI6MjA2MzczMTQ4Nn0.oEMJaE2BUjmX8UI2z6ApZDPeKEtM6BeG0vbgYvGW3AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);